title: "Zachary Weissman"
author: "Blog Author"
description: "Georgia Institute of Technology"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:
  - {file: "index.html", title: "Home"}
  - {file: "projects.html", title: "Projects"}
  - {title: "CV", url: "/assets/Zachary_Weissman_Resume.pdf"}
  - {file: "experience.html", title: "Experience"}
  - {file: "activities.html", title: "Activities"}
  - {file: "skills.html", title: "Skills"}


external:
  - {title: "Email", url: "mailto:zacharyweissman3@gmail.com", icon: "envelope"}
  - {title: "GitHub", url: "https://github.com/zweissman6", icon: "github"}
  - {title: "LinkedIn", url: "https://linkedin.com/in/zachary-weissman", icon: "linkedin"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
